### ISSUE TITLE
Make upper case for `h2` optional

### ISSUE THREAD

**Issue by clsty** [bowman2001/perplex#162]
Hi, I've noticed that all `h2` elements becomes all upper case, and I personally don't want that.

Could you please tell me how to disable this behavior? Thanks in advance.

**Comment by clsty** [comment]
I've solved this by customing CSS in `assets/css/custom/custom.css`:
```css
.md--h-sans > h2 { text-transform: none; }
.section > h2 { text-transform: none; }
.md--footer > h2 { text-transform: none; }
.nav-main__link { text-transform: none; }
```
