### ISSUE TITLE
Dynamic top nav bar

### ISSUE THREAD

**Issue by Kariton** [bowman2001/perplex#168]
Hey,

can the top navigation bar be more dynamic?
currently "[NEWS](https://perplex.desider.at/) [DOCS](https://perplex.desider.at/doc/) [BLOG](https://perplex.desider.at/blog/) [ABOUT](https://perplex.desider.at/authors/georg-makowski/)" seem to be static.

i would love to see the option to rename them and add more.
especially something like a "on hover dropdown" menu thing.

so like:
```
DOCS
> big doc topic -> docs page as usual for that "big doc topic"
> another topic -> docs page as usual for "another topic"
```

to keep feature compatibility it could be hidden behind some "extended menu" flag.
```yaml
extended_top_menu: true
top_menu:
  - title: "NEWS"
    path: none # -> default to /
    weight: 1
  - title: "DOCS"
    path: "doc"
    weight: 2
    children:
      - title: "big doc topic"
        path: "big_doc_topic"
        weight: 1
      - title: "another topic"
        path: "another_topic"
        weight: 2
[...]
```

the file structure should be self explanatory:
```
/content/doc/big_doc_topic/file.md 
/content/doc/big_doc_topic/folder/file.md 
```
same goes for urls:
```
http://localhost:1313/doc/big_doc_topic/file/
http://localhost:1313/doc/big_doc_topic/folder/file
```
where `http://localhost:1313/doc/` is just a summary page like those for tags or categories.
